### ISSUE TITLE
Corrrect current watering day handling

### ISSUE THREAD

**Issue by maksym-shlakhtun** [ValentiWorkLearning/OOP_Lab_Flowerpoot#1]
https://github.com/ValentiWorkLearning/OOP_Lab_Flowerpoot/blob/7dac2d339a752b7e84a0e5367d7395ef0691ccfa/flowers/floweringhouseplant.cpp#L97

void FloweringHouseplant::makeWatering()
{
	
	if ( logic_isWateringAtTime() )
	{
		if (getFlowerStatus() == FlowerState::Flowering)
		{
			m_isCorrectWateringInFlowering = true;
		}
		else
		{
			m_currentWaterings++;
			setLastWateringDate( Date() );
			if (m_currentWaterings == m_needdedSuccesfulWaterings) m_flowerStatus = FlowerState::Flowering;
		}
		return;

	}
	if (logic_isWateringBeforeAfter1Day())
	{
		if (getFlowerStatus() == FlowerState::Flowering)
		{
			m_isCorrectWateringInFlowering = true;
		}
			setLastWateringDate( Date() );
		return;
	}
	else
	{
		if (getFlowerStatus() == FlowerState::Flowering) //If flowering process - reset the corrects waterings 
		{
			m_isCorrectWateringInFlowering = false;
		}
		else
		{
			if (m_currentWaterings)m_currentWaterings--;
		}
		setLastWateringDate( Date() );
	}
}

**Comment by ValentiWorkLearning** [comment]
Поправил, теперь работает как положено.
